In [1]:
import numpy as np

In [4]:
mylist = [1,2,3]
x = np.array(mylist)
print(x)

y = np.array([4,5,6])
print(y)

m = np.array([[7,8,9], [10,11,12]])
print(m)

[1 2 3]
[4 5 6]
[[ 7  8  9]
 [10 11 12]]


In [5]:
matrix = np.array([[4,3,1],[5,2,6],[1,1,1]])
print(matrix)

[[4 3 1]
 [5 2 6]
 [1 1 1]]


In [6]:
print(m.shape)

(2, 3)


In [11]:
n = np.arange(0,30,2)
print(n)

n = n.reshape(3,5)
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [17]:
o = np.linspace(0,4,9)
print(o)

t = np.linspace(1,10,20)
print(t)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [19]:
o.resize(3,3)
print(o)

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


In [29]:
ones = np.ones((3,2)) # 1 가득 행렬
print(ones)

zeros =np.zeros((2,3)) # 0 가득 행렬
print(zeros)

eye = np.eye(3) # 단위행렬
print(eye)

diag = np.diag(y)
print(y)
print(diag)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[4 5 6]
[[4 0 0]
 [0 5 0]
 [0 0 6]]


In [36]:
rep = np.array([1,2,3] * 3)
print(rep)

rep1 = np.repeat([1,2,3], 3)
print(rep1)

rep2 = np.repeat(['a', 'b', 'c'], 4)
print(rep2)

p = np.ones([2,3])
print(p)

v = np.vstack([p, 2*p]) # 행렬을 수직결합
print(v)

h = np.hstack([p, 2*p])
print(h)

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]
['a' 'a' 'a' 'a' 'b' 'b' 'b' 'b' 'c' 'c' 'c' 'c']
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]]


In [42]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [44]:
x.dot(y) # dot product 연산 1*4 + 2*5 + 3*6

32

In [50]:
z = np.array([y, y**2])
print(len(z))

print(z)

t = z.T
print(t)

z.dtype

2
[[ 4  5  6]
 [16 25 36]]
[[ 4 16]
 [ 5 25]
 [ 6 36]]


dtype('int32')

In [51]:
z= z.astype('f')
z.dtype

dtype('float32')

In [70]:
s = np.arange(13) ** 2
print(s)

a,b,c = s[0], s[4], s[-1] # 인덱싱

print(a,b,c)

print(s[1:5])

print(s[-4:])

print(s[-5::-2])

r = np.arange(36)
print(r)
r.resize((6,6))
print(r)

print(r[2,2])

print(r[3, 3:6])

print(r[:2, :-1])

print(r[-1, ::2]) # 마지막행 0부터 오른쪽 방향으로 2씩 데이터 출력 # [30, 32, 34]

print(r>30) # t/f

print(r[r>30])

[  0   1   4   9  16  25  36  49  64  81 100 121 144]
0 16 144
[ 1  4  9 16]
[ 81 100 121 144]
[64 36 16  4  0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
14
[21 22 23]
[[ 0  1  2  3  4]
 [ 6  7  8  9 10]]
[30 32 34]
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False  True  True  True  True  True]]
[31 32 33 34 35]


In [73]:
r[r>30] = 30
print(r)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [ ]:
# Refered by https://engkimbs.tistory.com/ 